//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P4Papi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Point
    {
        public System.DateTime YM { get; set; }
        public int UserId { get; set; }
        public double MonthlyPoint { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
    
        public virtual User User { get; set; }
    }
}
