//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P4Papi
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLoginDepartment
    {
        public int UserLoginDepartmentId { get; set; }
        public int UserLoginId { get; set; }
        public int DepartmentId { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual LoginUser LoginUser { get; set; }
    }
}
